In [ ]:
#1. Create a numpy array containing the numbers from 1 to 10 and then reshape it to a 2x5 matrix.

In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b=a.reshape(2,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#2. Create a numpy array containing the numbers from 1 to 20 and then extract the elements between the 5th and 15th index.

In [ ]:
v=np.arange(1,21)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
v[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
#3. How to compute the mean, median,and standard deviation of a numpy array? Use the array you created above.

In [ ]:
print(np.mean(v))
print(np.median(v))
print(np.std(v))

10.5
10.5
5.766281297335398

In [ ]:
#4. Write a NumPy program that creates a 2D array x of shape (3,4) and 1D array y of shape(4). subtract y from each row of x using broadcasting.

In [ ]:
x=np.arange(5,28,2)
print(x)
y=np.arange(1,5)
print(y)

[ 5  7  9 11 13 15 17 19 21 23 25 27]
[1 2 3 4]

In [ ]:
c=np.reshape(x,(3,4))
print(c)
n=y.reshape(4)
print(n)

[[ 5  7  9 11]
 [13 15 17 19]
 [21 23 25 27]]
[1 2 3 4]

In [ ]:
print(c-n)

[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]]

In [ ]:
#5. Create a dataframe with the following columns:name,age,and gender.The data frame should have 10 rows of data.

In [ ]:
import pandas as pd

In [ ]:
a=pd.DataFrame({"name":["gegi","vino","abhi","anu","sne","ash","deepu","appu","haris","ammu"],"age":[36,23,21,21,21,33,28,34,25,21],"gender":["f","m","f","f","f","f","f","m","m","f"]})
a

    name  age gender
0   gegi   36      f
1   vino   23      m
2   abhi   21      f
3    anu   21      f
4    sne   21      f
5    ash   33      f
6  deepu   28      f
7   appu   34      m
8  haris   25      m
9   ammu   21      f

In [ ]:
a["occupation"]=["programmer","manager","analyst","programmer","manager","analyst","programmer","manager","analyst","programmer"]
a

    name  age gender  occupation
0   gegi   36      f  programmer
1   vino   23      m     manager
2   abhi   21      f     analyst
3    anu   21      f  programmer
4    sne   21      f     manager
5    ash   33      f     analyst
6  deepu   28      f  programmer
7   appu   34      m     manager
8  haris   25      m     analyst
9   ammu   21      f  programmer

In [ ]:
v=a[a["age"]>=30]
v

   name  age gender  occupation
0  gegi   36      f  programmer
5   ash   33      f     analyst
7  appu   34      m     manager

In [ ]:
a.to_csv("employees.csv",index=False)

In [ ]:
b=pd.read_csv("employees.csv")
b

    name  age gender  occupation
0   gegi   36      f  programmer
1   vino   23      m     manager
2   abhi   21      f     analyst
3    anu   21      f  programmer
4    sne   21      f     manager
5    ash   33      f     analyst
6  deepu   28      f  programmer
7   appu   34      m     manager
8  haris   25      m     analyst
9   ammu   21      f  programmer